### ISSUE TITLE
Fehlender gitlab container (synology_gitlab)

### ISSUE THREAD

**Issue by tobidemski** [jboxberger/synology-gitlab-jboxberger#1]
Reference to https://github.com/jboxberger/synology-gitlab/issues/23

Hey, da ich mir gestern mein Gitlab zerschossen habe, habe ich gedacht ich versuche mal einen clean install von deinem neuen Installer welcher mit postgresql läuft.

Nachdem ich alles voll konfiguriert habe und alles erfolgreich installiert habe, habe ich wieder festgestellt das alle Container da waren außer "synology_gitlab" (Alle Images waren vorhanden). Sprich das Problem von mir damals ist wieder da.
Kann es vielleicht sein das dein Setup auf irgendwas bestimmtes zugreift welches nicht den Zugriff über die Domain erhält außer ich trage "localhost" ein?

Nachdem ich alles wieder komplett gelöscht habe und für den Installer "localhost" eingetragen habe ging alles problemlos. Sprich alle drei Images sowie Container waren vorhanden und ich konnte nach Anpassung der Domain das Paket erfolgreich starten.

**Comment by jboxberger** [comment]
Hi D4rkiii,
ich habe versucht es nachzustellen aber leider ohne Erfolg. :-( Ich installiere immer mit einem anderen Namen host "localhost".  Ich vermute das möglichweise deine Konfiguration oder andere Umstände zum Problem führen.

![grafik](https://user-images.githubusercontent.com/1545845/36926613-0dee36ec-1e79-11e8-90d2-20d2c8ecbcfb.png)

Könntest du versuchen den Fehler zu reporduzieren und mir anschließen die Fehler aus der
/var/log/synopkg.log zur Verfügung stellen? Könntest du mir bitte ebenfalls sagen welche DS du hast, wieviel RAM verbaut ist und welche DSM & Docker Version du verwendest. 

Danke für das Reporting!

Gruss Juri

**Comment by tobidemski** [comment]
Clean Install [X]
 - Gitlab Data + repos gelöscht beim vorherigen deinstallieren

Hardware:
DS: 916+
RAM: 8GB
DS Version: DSM 6.1.5-15254
Docker Version: 17.05.0-0367

Gitlab Version: synology-gitlab-jboxberger-aio-10.5.1.spk
Host: gitlab.xxx.de
Port: 443
SSH: 30001
Docker Port Mapping: 443 --> 30000

DSM Reverse Proxy:
443 --> 30000

Mail Einstellungen: 
Unsichere Verbindungen zulassen: [X]

Nach Installation ausführen: [ ]

Synopkg.log: https://pastebin.com/3y3eLd2Y (Passwörter / Domain wurde anonymisiert)

Anscheinend gibt es Fehler bei "Generating OpenSSH host keys..."...
SSH sowie das Web sind aber von außerhalb Aufrufbar.

**Comment by jboxberger** [comment]
Benutzt du bei den "Mail Einstellungen:" Gmail & SSL?

**Comment by tobidemski** [comment]
Ne ich benutze bei den Mail Einstellungen meinen eigenen Mail Server.
Testweise kann ich auch gerne ohne Mail Einstellungen die Installation versuchen wenn du vermutest das es daran liegen könnte (Was ich dann aber eher komisch finden würde).
(SSL ist dabei aus)

Edit: 

Ohne Mail Einstellungen das selbe Problem.

**Comment by jboxberger** [comment]
Ok super! Habe den fehler schon lokalisiert und versuche den nachzustellen und zu beheben!
"{
   "error" : {
      "code" : 1303,
      "errors" : {
         "errors" : "443,30001"
      }
   },
   "httpd_restart" : false,
   "success" : false
}"

Danke für dein log!

**Comment by jboxberger** [comment]
Nur ein Gedanke: "Ist es möglich dass der Port 443 bereits durch einan andere Applikation belegt ist bzw. die DS den Port noch nicht freigegeben hat?" 

Wenn das so wäre müsste ein reboot zw. dem Install und Uninstall nicht zu dem Fehler führen. Könntest du das bitte prüfen wenn du Zeit hast.

PS: Email brauchst du nicht ändern, es gibt nur ein bekanntes Problem mit GMAIL und SSL innerhalb von Gitlab. Wollte das nur vorher ausschließen. Bei dir ist das Problem klar der SSL 443 Port. Irgendwo da müssen wir "buddeln" :-)

**Comment by tobidemski** [comment]
Würde das aber nicht bedeuten das ich dann niemals updaten könnte weil das Problem dabei auch bestehen würde?
Kann das Problem vielleicht dabei bestehen das ich von meinem Router 443 -> DS weiterleite und von dort aus der Reverse Proxy für meine Domain an den Docker schickt welches evtl. noch nicht valide ist weil ich im Anschluss über ein Script die SSL Certs von Lets Encrypt in den Ordner von gitlab kopiere.

Ich hab gerade  noch das Gefühl das etwas mit den Port Bindings etwas nicht stimmt.
Im Log bei "Generating OpenSSH host keys" steht:
port_bindings":[{"container_port":80,"host_port":"443","type":"tcp"},{"container_port":22,"host_port":"30001","type":"tcp"}

--> container_port":80, dürfte ja niemals vorkommen wenn ich für mein Web HTTPS verwende.

(Reverse Proxy... Leite für hostname gitlab.DOMAIN.de:443 auf localhost:3000 weiter)
Dementsprechend müsste eigentlich als Container Port 30000 stehen



Deinen Versuch kann ich aber auch gerne noch testen

**Comment by jboxberger** [comment]
OK das Problem kann ich schon mal nachstellen, das ist schon mal SEHR GUT! VIelen Dank dafür!
Ich schaue mir das mal heute abend genauer an und melde mich dann.

Ja bei den PortBindings vermute ich auch das Problem... ich prüfe das heute abend.

**Comment by tobidemski** [comment]
Super! Ich denke das man im Installer noch eine Option brauch um den Container Port definieren zu können.

**Comment by jboxberger** [comment]
Bei GitLab muss bei 443 auch GITLAB_HTTPS, SSL_KEY_PATH, SSL_CERTIFICATE_PATH und SSL_SELF_SIGNED  gesetzt werden :-) Aber das würde nur dazu führen das du den container nicht erreichen kanns, obwohl dieser problemlos in docker angelegt wurde.  

MAchen wir ein Problem nach dem anderen :-)

**Comment by tobidemski** [comment]
Dann brauchen wir noch eine Option um HTTPS über ein Flag zu aktivieren :D
An den Paths habe ich bisher nichts verändert, soweit ich weiß hat gitlab dafür standard Werte definiert und habe bisher auch nur die SSL Certs in gitlab verschoben und damit hat es auch funktioniert.

DOKU aus dem Repo:

The default path that the gitlab application is configured to look for the SSL certificates is at /home/git/data/certs, this can however be changed using the SSL_KEY_PATH, SSL_CERTIFICATE_PATH and SSL_DHPARAM_PATH configuration options.


BTW. es ist nicht self signed da ich die Certs mit der DSM aus Lets Encrypt beziehe.

**Comment by jboxberger** [comment]
Wenn du möchtest kannst du das Problem umgehen indem du normal ohne 443 installiert und das SSL naträglich im docker änderst. Beim Update habe ich mitllerweile eine Lösung implementiert das alle docker ENVIRONMENT Variablen und Ports beim Update mit übernommen und du das Update eigentlch auch mit SSL problemlos durchführen können solltest. 

Du kannst es ja mit 10.4.2 ink. SSL auf 10.5.1 probieren. Müsste klappen, *daumendrück*.

**Comment by tobidemski** [comment]
Ich glaube hier ist das Problem das ich mit dem Reverse Proxy arbeite um für die Domain auf die Docker Container zu mappen.

Sobald ich meine Domain Eintrage, klappt es nicht, dementsprechend ist derzeit mein Workaround den Host auf localhost zu lassen um den nach der Installation zu ändern.

Nur selbst ein Update klappt anschließend nicht richtig :/
Vermutlich werden beim Update nicht die vorhandenen Container Ports verwendet sondern die Default (wieder 80).

EDIT: Okay eine Installation mit Port 443 scheint generell derzeit das Problem zu sein

**Comment by jboxberger** [comment]
Ja es ist definiv der Port 443. Normalerweise lässt man z.B. den Port 30000 und der interne Container Port zeigt dann auf 443... das habe ich jetzt soweit drinn mein Problem ... ich kriege auf meiner Synology das .pem nicht generiert.... da passier teinfach NICHTS ....

sudo openssl dhparam -out dhparam.pem 2048 

![grafik](https://user-images.githubusercontent.com/1545845/36956097-b4620436-202c-11e8-8e0c-408a9e65bc44.png)

So bleibt es dann einfach stehen... auf meinem ubuntu system kann ich die .pem problemlos generieren. Hast du das Problem auch?

**Comment by jboxberger** [comment]
Bist du sicher dass du den Synology 443 Port überhaupt auf einen Container anwenden kannst?
Bei mir klappt es nicht:

![grafik](https://user-images.githubusercontent.com/1545845/36956621-ab26b5da-202f-11e8-803e-f6f2c1beee33.png)

30443 kappt dagegen problemlos...

**Comment by tobidemski** [comment]
Ja das Problem mit der Datei hatte ich auch, habe dann auch gelesen das es solch eine Datei bei Synology schon gibt. Pfad: /usr/syno/etc/ssl (Info aus: https://chpresearch.wordpress.com/2016/10/04/synology-gitlab-setup-ssl-over-lets-encrypt/ ). habe mir dann einfach daraus die Datei genommen.

Zusätzlich lasse ich derzeit als Task Runner folgendes Script laufen (Angepasst an meine Domain) http://www.synology-forum.de/showthread.html?76034-Docker-von-Extern-und-HTTPS-mit-GitLab/page3&p=711914&viewfull=1#post711914

Um immer die aktuelle Certs für meine gitlab Domaine zu haben. (Könntest du evtl. irgendwann mal mit in dein AIO hinzufügen für SSL via Lets Encrypt Support ;) )

Ich habe folgende Einstellungen im Docker Container:
Lokal 30000 | Container 443
Lokal 30001 | Container 22

gitlab.domain.de als Domain

Anschließend alles was mit Web zu tun ( 80 | 443) habe ich im Router auf die NAS weitergeleitet.
Domain hat die IP von Zuhause (Über OVH Host gesynced).
Dann unter Reverse Proxyeinen Eintrag gemacht welches gitlab.domain.de:443 auf localhost:30000 weiterleiten soll.


Ich vermute das meine Konstellation bzgl. der Domain / Weiterleitung etc. nicht mit dem Script funktioniert da ich ja im Endeffekt über Umwege zum Ziel (Gitlab) komme welches während der Installation wohl nicht im Scope liegt.

**Comment by jboxberger** [comment]
Hi D4rkiii, danke für den Tipp mit der dpharm datei! Das hat echt weiter geholfen.

Ich denke ich habe jetzt eine gute Lösung. Es ist nicht mehr möglich die Host-Ports 22, 80 oder 443 direkt zu verwenden. Die Container Ports werden jetzt richtig gesetzt und auch die Verknüpfung verlinkt auf https. Bei SELF_SIGNED werden die Zertifikate automatsich generiert. 

![gitlab](https://user-images.githubusercontent.com/1545845/37124478-af878038-2268-11e8-8a33-e10e82ce2c96.png)

Das Problem was du hattes wäre damit ja eigentlich gelöst oder? Ich habe alle Realeases aktualsiert und sie beinhalten jetzt diese Feature.

PS: Die Synology unterstütz von Haus aus LetsEncrpyt, du kannst hier dein zertifikat Anlegen/Konfigurieren und anschließend einfach in den "/volume1/docker/gitlab/certs" Ordner kopieren.

![grafik](https://user-images.githubusercontent.com/1545845/37124586-3e367fd2-2269-11e8-88fb-5d416224df47.png)

Gruss

**Comment by tobidemski** [comment]
Hey Danke dir schon mal für den Support, Super Arbeit die du da machst.

Bzgl. des Lets Encrypt Zertifikats... Ja das mache ich bereits so, aber jedes mal das Zertifikat manuell zu verschieben wäre ja lästig, deswegen der Link im vorherigen Posts welcher das automatisch für dich macht ;) ( http://www.synology-forum.de/showthread.html?76034-Docker-von-Extern-und-HTTPS-mit-GitLab/page3&p=711914&viewfull=1#post711914 )

Man erstellt im Aufgabenplaner einfach eine neue geplante Aufgabe und trägt das Script ein. Anschließend sucht er in den Zertifkaten von Synology (Nachdem einmalig Lets Encrypt für die Gitlab Domaine eingerichtet wurde) nach dem Zertifikat für Domain X (Im Script eingetragen) und verschiebt es an die Stelle von Gitlab (/volume1/docker/gitlab/certs).

Wäre ja cool wenn das beim ersten installieren deines AiO-Scripts mit Hinzugefügt würde. Würde auf jeden Fall den Support für HTTPS in deinem Package weiter ausfahren :P

Gruß
Tobi

**Comment by jboxberger** [comment]
Hi Tobi,
ich habe mir das Script näher angeschaut, es ist ein script das in den syno zertifikaten nach dem cert mit der gitlab domain sucht und dieses in das gitlab/cert verzeichnis kopiert. Ich habe es an das paket angepasst. Kannst du prüfen ob es automatisiert dein Letsencrypt Zertifikat findet und korrekt in Gitlab importiert? Achtung du musst das paket als SSL / SSL_SELF_SIGNED installiert haben.

Einfach das script nach `/var/packages/synology-gitlab-jboxberger/scripts/` kopieren und als **admin** ausführen. [import-syno-cert.zip](https://github.com/jboxberger/synology-gitlab-jboxberger/files/1795281/import-syno-cert.zip)

Dein LetsEncrypt cert solle erfolgreich importert werden. Später kann man das script eventuell vor dem container start ausführen um immer das aktuelle cert zu haben.

Offen Fragen: 
- Berechtigung der cert 400 ???
- Was passiert wenn ein anderes cert bereits vorhanden ist. > added --force-renew parameter

PS: Ich habe die Releases 10.4.2 und 10.5.1 aktualisiert, diese beinhalten dann bereits das import-syno-cert script

Gruss

**Comment by kopfpilot** [comment]
Das Skript stammt von mir. Ich nutze in unterschiedlichen Foren gerne unterschiedliche Nicks ;) Wenn es mit Berechtigungsmaske 400 läuft ist natürlich besser. Ich hatte 444 gesetzt, da es damit lief und Gitlab es akzeptiert hat. Bei anderen Berechtigungsmasken wollte Gitlab partout nicht starten. Was mich wundert ist die 400er Maske funktioniert ohne chown?  Das würde ja bedeutet, dass Gitlab als root läuft?! 

Das Skript ist so angelegt, dass es nur dann die Zertifikatsdateien kopiert, wenn diese in der Quelle neuer sind als am Ziel.

Was mich an dem Reverse-Proxy szenario wundert: Warum ein doppelter HTTPS-Kontext?

Entweder man nutzt HTTPS vom Container, dann muss der WAN-Port direkt auf den DSM-Port des Containers weitergeleitet werden. oder man macht HTTPS offloading und beendet HTTPS im Syno-Reverseproxy und gibt intern über HTTP weiter. Die externe URL kann man über ENV-Parameter konfigurieren.

Der Syno-Reverse-Proxy ist ziemlich eingeschränkt. Normalerweise kann nginx deutlich mehr: 
- TCP-Balancing: eingehender Port wird direkt auf Ziel:Port weitergeleitet
- SSL Pass-thru: ohne die Daten zu entschlüsseln wir der verschlüsselte Trafik direkt an Ziel:Port weitergeleitet. Das klappt dank TLS-Erweiterung SNI, welche erlaubt zu erkennen für welche Domain die Daten sind.

**Comment by kopfpilot** [comment]
Folgende Zeile ist so nicht notwendig:
`cat ${current_domain_cert}/cert.pem ${current_domain_cert}/fullchain.pem > ${GITLAB_CERT_DIR}/${GITLAB_CERT}`
Stattdessen ist folgendes ausreichend
`cp ${current_domain_cert}/fullchain.pem ${GITLAB_CERT_DIR}/${GITLAB_CERT}`

Hintergrund: fullchain.pem besteht aus cert.pem und chain.pem, so dass ein zusätzliches hinzufügen von cert.pem keinen Vorteil bietet.

Nette Erweiterung des Scripts btw.! Force hatte ich bei mir auch schon lange eingebaut. Aber den Container restart über Syno-Mittel zu machen ist natürlich charmant.

**Comment by jboxberger** [comment]
Hi @kopfpilot,

erstmal vielen Dank für dein script! Ich selber bin recht neu in der SSL Welt daher war deine Vorarbeit für mich perfekt! Hast du eventuell einen File Header mit deinen Creds den ich in das File einbauen kann. Ehre dem wem Ehre gebührt :-)!

Ja der nginx läuft mit root aber irgendwie auch nicht. Bin da kein Experte aber das läuft alles intern im sameersbn/gitlab docker container ab und da habe ich keinen Einfluss. Die standard Files werden im share mit owner 1000 abgelegt. Habe mich aber offengestanden nicht damit befasst da alles funktioniert hat und wundere mich aktuell auch wo ich grad drüber schau...
![grafik](https://user-images.githubusercontent.com/1545845/39972297-625c9fd6-570c-11e8-865e-1f84d2e18a05.png)

Ja die die Terminierung durch die Synology wäre sinvoller aber es gibt halt viele die nicht wissen wie sowas geht (so wie ich weil ich es nie gebraucht habe) und dann die "einfache/bekannte" Lösung suchen.
Es wurde mehrfach angefragt darum habe ich mich bemüht eine Lösung zu schaffen. Für mich gehört mein privates Repo nicht ins Netz und meine DS ist auch nicht im Netz... heutzutage ist es Wahnsinn die DS mit den wichtigsten daten die man besitzt und mir einem Linux 3.10 Kernel ins netz zu hängen... Aber ich denke jeder der Gitlab einsetzt hat mit Technick und Entwicklung zu tun und weiss genau was er tut.

Danke auf jeden Fall für deinen Beitrag, deine Vorschlag im script habe ich übernommen.

Gruss

**Comment by kopfpilot** [comment]
Vielen Dank mit dem File-Header-Angebot. Die Benutzung alleine ist schon Anerkennung genug.

Das sameersbn/gitlab Image erlaubt User-Mapping mittels USERMAP_UID und USERMAP_GID.
Container mit User-Mapping startet meistens als Root, modifizieren die IDs des beschränkten Benutzers der den Hauptprozess startet und starten dann genau diesen. Die Motivation für das User-Mapping ist eigentlich recht einfach: so kann man sicherstellen, dass der "richtige" Benutzer auf gemappte Volumes zugreift und man so keine Berechtigungsprobleme bekommt.

Mir ist auch nicht ganz klar, ob der nginx das SSL-Offloading macht, oder ob es bis zum Ruby-Prozess durchgereicht wird. Da aber die Zertifikate sauber eingebunden werden, scheint es ja zu passen.
