### ISSUE TITLE
Update to Latest Gitlab Release 11.5.1

### ISSUE THREAD

**Issue by helmut-steiner** [jboxberger/synology-gitlab-jboxberger#11]
Hey Juri,
I guess you are quite busy at the moment but it would be great if you could update the sources to use the latest Gitlab release to incorporate the security fixes.
Thanks in advance,
Helmut

**Comment by jboxberger** [comment]
Currently only 11.5 is available at sameersbn dockr repo. I've updated the package.

**Comment by helmut-steiner** [comment]
Thank you! Yeah the update to 11.5.1 was just released as I wrote you. I thought that by the time you react it would be available over at sameersbn's repo. You were just too fast. Sameer updated shortly after you commited.
As always, thanks for your work!
