### ISSUE TITLE
Restore backup from Omnibus package

### ISSUE THREAD

**Issue by nexxome** [jboxberger/synology-gitlab-jboxberger#2]
Hi,
at the moment I'm running the Gitlab Omnibus package on a Raspberry Pi, but because it is really slow I'm thinking about migrating to my DS.

I installed your DS package without a problem and all is running fine, but I'm not sure how to restore the backup .tar file created with "gitlab-rake gitlab:backup:create" from the pi.

As I understand the backup file differs from the one created by your backup script, so your restore script would not work. Can you give me a hint?

Kind Regards

**Comment by jboxberger** [comment]
Hi,
yes my backup script intend to backup gitlab and also the environment configuration, so i simply dump the Docker Config, DB and the GitLab share folder. This backup would not help you. As far as i have seen your backup on your Pi should be located in you gitlab/backup folder. You can copy it on you DS to the gitlab backup location "/volume1/docker/gitlab/backup". After that you can bash into the gitlab container 
`sudo docker exec -it synology_gitlab_db bash` and start the restore with rake. Your backup files should be located at "/home/git/data/backup". I have nearly no expirience with rake so maybe you can teach me how to do that when you succeed i can made a small tutorial "how to migrate from omnibus installation" ;-)

Kind Regards

**Comment by nexxome** [comment]
Hi,
I copied the backup .tar to /volume1/docker/gitlab/backup and started the restore with

`sudo docker exec -u git -it synology_gitlab /home/git/gitlab/bin/rake gitlab:backup:restore BACKUP=...`

I think this should work, the problem at the moment is that the pi Gitlab version is 10.6.0, so I have to wait for this Synology Gitlab version

`Your current GitLab version (10.5.6) differs from the GitLab version in the backup!
  Please switch to the following version and try again:
  version: 10.6.0`

**Comment by jboxberger** [comment]
Hey that sounds great. 
Yes the the latest available GitLab package is at 10.5.6 but i think the 10.6.0 will come soon. I will let you know as soon as [sameersbn/gitlab](https://hub.docker.com/r/sameersbn/gitlab/) release it. 

Kind Regards

**Comment by nexxome** [comment]
Hi,
it is now released :)

Kind Regards

**Comment by jboxberger** [comment]
Cool, i will update tonight. :-)

**Comment by jboxberger** [comment]
Update is done! 👍 
Hope everything works for you!

Kind Regards

**Comment by nexxome** [comment]
I think it worked :)

On restoring the database i got some of these errors:

`role "gitlab" does not exit`

But at the moment I don't see any problems.
I also run a gitlab check and no errors occured:

`sudo docker exec -u git -it synology_gitlab /home/git/gitlab/bin/rake gitlab:check`

So here again the steps to restore the backup from the Omnibus installation:

1. Run `sudo gitlab-rake gitlab:backup:create STRATEGY=copy` on the machine with the Omnibus installation
2. Copy the created backup .tar file from /var/opt/gitlab/backups to /volume1/docker/gitlab/backups on the DS
3. Run `sudo docker exec -u git -it synology_gitlab /home/git/gitlab/bin/rake gitlab:backup:restore BACKUP=...`
4. If there are users with two-factor authentication you also have to copy /etc/gitlab/gitlab-secrets.json, but I don't know the location for this file on the Docker image. More information are [here](https://docs.gitlab.com/ee/raketasks/backup_restore.html#storing-configuration-files).

Thank you for your help 👍 
Kind Regards

**Comment by jboxberger** [comment]
Ok the problem with the role should be solved if you use during the install "gitlab" instead of the "gitlab_user" as database user.

4. the folder you're searchinng for is "/home/git/gitlab/config" but there is one problem, it will be deleted on every update. Let check it the other way, i have no idea from Two-Factor-Auth on Gitlab. Try a celan install of GltLab 10.6.0 an create some users with Two-Factor-Auth  and now we have to find where the file is located. This command should help `find -L . -name "gitlab-secrets.json"`. I would expect to finde the file in the /volume1/docker/gitlab because it is persistent and otherwise it does not make sense. But i also have not found anything about it in the [sameersbn/gitlab](https://hub.docker.com/r/sameersbn/gitlab/) docs. :-(

**Comment by jboxberger** [comment]
Hi nexxome,

do you still need some help or is your problem solved? If you use the synology-gitlab-jboxberger package please migrate to my [synology-gitlab](https://github.com/jboxberger/synology-gitlab) or to the stock package, since this package will not be updated any more.

Kind Regards

**Comment by nexxome** [comment]
Hi,
thank you for your help. I'm still running version 10.6.0 from this repository. If I understand the documentation correctly, I have to update Gitlab to the version 11.5.0-0102 from this repository, and than migrate to 11.5.0-0053 from the new repository. Is this correct?
Kind Regards

**Comment by jboxberger** [comment]
Hi, yes this is absolutely correct, but there is a little Version missmatch, i fixed it in the description.

You need to update the following way:
10.6.0 (your_version)                                  ==> 11.5.1-0102 (synology_gitlab_jboxberger)
11.5.1-0102 (synology_gitlab_jboxberger) ==> 11.5.1-0053 (synology_gitlab)

Please backup anythig first and after each step. https://github.com/jboxberger/synology-gitlab#backup
Please note that you have to modify the container name from "synology_gitlab" to "synology_gitlab_jboxberger" as far as i can remember. 

Do not use the Backup function containing in the synology-gitlab-jboxberger, Use the native Gitlab Backup function from Gitlab directly (upper link). With this backup you can restore on any system (also on non synology systems) so far the Gitlab Version is the same.

If you got in trouble feel free to contact me and i will help as good as i can, if needed also on discord, no problem. Unfortunately i am on holiday from today afternoon until 25.02 so i cant answer to your requests. If you're not shure in that what you're doing, maybe you want to schedule your migration after this date so i can back you up.

Kind Regards
