### ISSUE TITLE
docker-gitlab issue have been resolved :)

### ISSUE THREAD

**Issue by dechowdev** [jboxberger/synology-gitlab-jboxberger#4]
Hi @jboxberger 

Thanks for a great package I am currently installing it on my NAS 👍 

I would just open an issue to inform you that the issue you are referencing in your readme under the info section have been resolved :)

https://github.com/sameersbn/docker-gitlab/issues/1617

Have a great day
- Lucas Dechow

**Comment by jboxberger** [comment]
Hi, thanks for the hint. I saw this already yesterday but there is now a problem with the SSL Encryption during update caused by my package. So the 10.8.3 build does not pass my tests. Hope i can get rid of the problem this week.

Kind Regards Juri

**Comment by jboxberger** [comment]
Hi Dechowmedia,

there is still one issue pending. Hope it get fixed soon. Please be patient.
https://github.com/sameersbn/docker-gitlab/issues/1627

Kind Regards Juri

**Comment by dechowdev** [comment]
Thats fine :) 
As long as the upgrade process will be smooth I am all aboard - I am migrating my repos from GitHub to my own private GitLab instance utilising your package.

**Comment by jboxberger** [comment]
Hi, with 11.0.0 The problem seems to be gone.

https://github.com/jboxberger/synology-gitlab-jboxberger/releases

Kind Regards
