### ISSUE TITLE
database password use '@' error

### ISSUE THREAD

**Issue by chodadoo** [jboxberger/synology-gitlab-jboxberger#6]
database password use '@' error

run this
'sudo ./var/packages/synology-gitlab-jboxberger/scripts/migrate-m10 --maria-db-root-password "xxxxx@" --maria-db-database "mdb10-gitlab-databse-name"'

i use password '@' -> Error...

(sorry i can't write english)

**Comment by jboxberger** [comment]
Hi chodadoo,

what error? Please paste the error message here. 

Do not use special Characters in Password, this cause [weird behavior](https://github.com/jboxberger/synology-gitlab-jboxberger/issues/5).

For Translation to your language you can use [Google Translate](https://translate.googleusercontent.com/translate_c?act=url&depth=1&hl=de&ie=UTF8&prev=_t&rurl=translate.google.com&sl=en&sp=nmt4&tl=de&u=https://github.com/jboxberger/synology-gitlab-jboxberger/issues/6&xid=17259,15700023,15700124,15700149,15700168,15700186,15700191,15700201,15700208&usg=ALkJrhh2Yzo8jMDF3BSQIq2_PEefDQUuDg).
