### ISSUE TITLE
synology gitlab -> synology-gitlab-jboxberger migration problem

### ISSUE THREAD

**Issue by chodadoo** [jboxberger/synology-gitlab-jboxberger#7]
hi, thanks for your answer

but, I have a new problem

my gitlab history
1. first using synology gitlab + mariadb 5
2. synology gitlab update (synology gitlab + mariadb 10)
- problem
3. mariadb 5 gitlab db, make 'gitlab.sql' file
4. mariadb 10 insert 'gitlab.sql'
5. complete gitlab
6. synology gitlab update (synology gitlab + postgresql)
- problem
7. synology gitlab uninstall (non remove local files)
8. synology-gitlab-jboxberger install
9. excute reference your manual
(sudo ./var/packages/synology-gitlab-jboxberger/scripts/migrate-m10 --maria-db-root-password "mdb10-root-password" --maria-db-database "mdb10-gitlab-databse-name")
- problem

9. problem log
[pgloader_log.txt](http://nas.inrose.com/tempory/pgloader_log.txt)

10. 'pgloader failed to find column' i try remove column
11. '9' step try
- problem
(ci_build_trace_chunks, ci_builds, foreign key and truncate bla bla...) sorry, i don't have log

this my mariadb 10 gitlab db tables struct

[gitlab_tables_struct.txt](http://nas.inrose.com/tempory/gitlab_tables_struct.txt)

**Comment by jboxberger** [comment]
Hello chodadoo,

when you migrate, to psotgre sql the Gitlab Version **HAS TO BE THE SAME**.

As you See in the LOG:
################################################################################
# WARNING!!! DATABASE VERSION MISMATCH DETECTED!!!
# **You can only migrate within GitLab one version. If the versions do not match, the**
# **migration will fail.** Matching example: MariaDB GitLab 10.1.4 to PostgreSQL GitLab 10.1.4.
# Continue only when you know what you're doing!
################################################################################

You can only migrate from 
9.4.4 to 9.4.4
10.1.4 to 10.1.4
10.2.5 to 10.2.5

You CAN NOT Migrate:
9.4.4 to 10.1.4
10.1.4 to 10.2.5

Please install the same Version of Postgresql Gitlab (synology-gitlab-jboxberger) as your mariadb 10 synology-gitlab package and retry migration. 

Pleas note, as long as you not delte the mysql and your gitlab data directory, you can always go back (revert) to the prevously unistalled mariadb 10 package.

Kind Regards

**Comment by chodadoo** [comment]
T^T i can't migration

last use synology gitlab
Version: 9.4.4-0050
(2017-12-13)

try synology-gitlab-jboxberger 9.4.4-0100
your script migrate failed
because my 'mariadb 10 tables' struct is different '9.4.4 mariadb 10 tables' struct !!! T^T

maybe... i have lower gitlab version mariadb struct

so i abandonment T^T

thanks for your answer
